data_list: [ '~/Documents/Kiin_AI/autoba_data/case1.1/SRR1374921.fastq.gz: single-end mouse rna-seq reads, replicate 1 in LoGlu group',
            '~/Documents/Kiin_AI/autoba_data/case1.1/SRR1374922.fastq.gz: single-end mouse rna-seq reads, replicate 2 in LoGlu group',
            '~/Documents/Kiin_AI/autoba_data/case1.1/SRR1374923.fastq.gz: single-end mouse rna-seq reads, replicate 1 in HiGlu group',
            '~/Documents/Kiin_AI/autoba_data/case1.1/SRR1374924.fastq.gz: single-end mouse rna-seq reads, replicate 2 in HiGlu group',
            '~/Documents/Kiin_AI/autoba_data/case1.1/TruSeq3-SE.fa: trimming adapter',
            '~/Documents/Kiin_AI/autoba_data/case1.1/mm39.fa: mouse mm39 genome fasta',
            './Documents/Kiin_AI/autoba_data/case1.1/mm39.ncbiRefSeq.gtf: mouse mm39 genome annotation' ]
output_dir: './examples/case1.1/output'
goal_description: 'find the differentially expressed genes'
meta:
    info: 'meta-data recorded by users for reference only'
    title: 'The transcriptional landscape of mouse beta cells compared to human beta cells reveals notable species differences in long non-coding RNA and protein-coding gene expression, '
    url: 'https://pubmed.ncbi.nlm.nih.gov/25051960/'
